services:
  - type: web
    name: safarnama-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: safarnama-postgis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: safarnama-postgis
    plan: free
